# Run command: docker-compose up -d

version: '3'

services:
  backend:
    build:
      context: ./fullstack_django
    ports:
      - "8000:8000"
    volumes:
      - .:/code

  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/code